// import "@/styles/globals.css";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import CenterLgScreen from "../common/CenterLgScreen";
import Footer from "../common/Footer";
import Header from "../common/Header";
import SideBar from "../common/SideBar";
import TopNav from "../common/TopBar";
import "../globals.css";

const rubik = Rubik({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn("min-h-screen font-sans antialiased", rubik.variable)}
      >
        <Header />
        <TopNav />
        <SideBar />
        <main className="lg:container lg:mx-auto">
          <CenterLgScreen>{children}</CenterLgScreen>
        </main>
        <Footer />
      </body>
    </html>
  );
}
